/**
 * components/PrintDocument.jsx
 * ----------------------------
 * Print-only rendering of a chat conversation: a professional cover page
 * followed by the full conversation rendered with the shared MarkdownRenderer
 * (so code blocks, tables, callouts and math look identical to the chat UI).
 * Portaled to <body> and shown only while printing (see `.print-root` CSS).
 */
import { createPortal } from "react-dom";
import MarkdownRenderer from "./MarkdownRenderer";

const PrintDocument = ({ video, messages = [] }) => {
  const questions = messages.filter((m) => m.role === "user").length;
  const answers = messages.length - questions;

  return createPortal(
    <div className="print-root">
      {/* ---- Cover page ---- */}
      <section className="print-cover">
        <div className="print-cover-brand">YT Chat GenAI</div>
        <h1 className="print-cover-title">Conversation Export</h1>
        {video?.thumbnail ? (
          <img className="print-cover-thumb" src={video.thumbnail} alt="" />
        ) : null}
        <h2 className="print-cover-video">{video?.title || "Untitled video"}</h2>
        <div className="print-cover-meta">
          <div>
            <span>Exported</span>
            <strong>{new Date().toLocaleDateString(undefined, {
              year: "numeric",
              month: "short",
              day: "numeric",
            })}</strong>
          </div>
          <div>
            <span>Messages</span>
            <strong>{messages.length}</strong>
          </div>
          <div>
            <span>Questions</span>
            <strong>{questions}</strong>
          </div>
          <div>
            <span>Answers</span>
            <strong>{answers}</strong>
          </div>
        </div>
      </section>

      {/* ---- Conversation ---- */}
      <section className="print-conversation">
        {messages.map((m, i) => {
          const isUser = m.role === "user";
          return (
            <article
              key={i}
              className={`print-msg ${isUser ? "print-msg-user" : "print-msg-ai"}`}
            >
              <div className="print-msg-role">{isUser ? "You" : "AI Assistant"}</div>
              {isUser ? (
                <p className="print-msg-user-text">{m.content}</p>
              ) : (
                <MarkdownRenderer className="print-md">{m.content}</MarkdownRenderer>
              )}
            </article>
          );
        })}
      </section>

      <footer className="print-footer">
        Generated by YT Chat GenAI · Premium AI Assistant
      </footer>
    </div>,
    document.body
  );
};

export default PrintDocument;
